-- NOTE: Image paths follow format: images/FolderName/filename.ext
--       Make sure corresponding image files exist in backend/Images/ folder
-- ============================================================================

-- ============================================================================
-- DATA FOR TABLE: places (32 tourism destinations)
-- ============================================================================
-- Insert or Update places with complete information

INSERT INTO places (id, name, category, city, image_url, rating, latitude, longitude, district, location, description, highlights, best_time_to_visit, how_to_reach, entry_fee, timings) VALUES
(1, '1000 Pillars Temple', 'Temples', 'Hanamkonda', 'images/1000Pillars/1000pillerstemple.jpg', 4.7, 18.00360000, 79.57480000, 'Hanamkonda', 'Hanamkonda, Telangana', 'The 1000 Pillars Temple, also known as Rudreshwara Swamy Temple, is an architectural marvel built in 1163 CE by the Kakatiya dynasty. This magnificent structure features intricate stone carvings and showcases unique star-shaped architecture. Each of its pillars is beautifully carved with mythological scenes and floral patterns.', 'UNESCO World Heritage nominee | Kakatiya dynasty architecture from 11th century | Intricate stone carvings on each pillar | Three sanctums for different deities | Massive Nandi sculpture | Star-shaped temple design', 'October to March offers pleasant weather ideal for exploring the temple complex. Early mornings (6-8 AM) provide peaceful atmosphere for photography and spiritual experience.', 'Located in Hanamkonda, 3 km from Warangal city center. Accessible by road via NH163. Regular bus services available from Warangal railway station and bus stand. Auto-rickshaws and taxis readily available.', 'No entry fee', '6:00 AM to 8:00 PM, Open all days'),

(2, 'Horsley Hills', 'Hills', 'Madanapalle', 'images/HorselyHills/Horsely_hills.jpg', 4.5, 13.65890000, 78.40470000, 'Chittor', 'Chittor, Andhra Pradesh', 'Horsley Hills is a enchanting hill station situated at an elevation of 4,312 feet above sea level, offering a perfect escape from the summer heat. Named after W.D. Horsley, a British collector, this destination is known for its eucalyptus forests, scenic viewpoints, and pleasant climate year-round.', '4,312 feet elevation with cool climate | Dense eucalyptus and sandalwood forests | Adventure activities: zip-lining, rappelling, trekking | Panoramic valley views and scenic viewpoints | Environmental education centre | Rich biodiversity with rare bird species', 'October to March when weather is most pleasant with temperatures between 15-25°C. Summer (April-June) also good for escaping heat with temperatures around 20-30°C.', 'Located 160 km from Bangalore and 60 km from Madanapalle. Accessible by road from Bangalore (3.5 hours), Tirupati (150 km), and Chennai (250 km). Nearest railway station: Madanapalle Road (40 km).', 'Entry: ₹30 per person, Vehicle: ₹50, Adventure activities: ₹200-500', '6:00 AM to 6:00 PM, Open all days'),

(3, 'Thalakona Waterfalls', 'Waterfalls', 'Sri Venkateswara National Park', 'images/Thalakona_Waterfalls/thalakona_waterfalls.jpg', 4.4, 14.03330000, 79.31670000, 'Tirupati', 'Tirupati, Andhra Pradesh', 'Thalakona Waterfalls, with a height of 270 feet, holds the distinction of being the highest waterfall in Andhra Pradesh. Located within the Sri Venkateswara National Park, this pristine waterfall cascades down rocky terrain creating natural pools perfect for bathing.', 'Highest waterfall in Andhra Pradesh at 270 feet | Natural pools for bathing and swimming | Trekking through Sri Venkateswara National Park | Medicinal herbs and rare plant species | Wildlife spotting opportunities | Therapeutic water with healing properties', 'July to February when waterfall is in full flow. Avoid monsoon peak (July-August) due to heavy rains. October-January ideal for trekking.', 'Located 50 km from Tirupati. Accessible by road via Chandragiri. Buses available from Tirupati to Mamandur (8 km from falls). From Mamandur, auto-rickshaws or 30-minute trek through forest.', 'Entry: ₹20 per person, Vehicle parking: ₹50, Camera: ₹25', '6:00 AM to 5:00 PM, Closed during heavy rains'),

(4, 'Warangal Fort', 'Forts', 'Warangal', 'images/Warangal_Fort/Warangal_Fort.jpg', 4.5, 17.95660000, 79.60210000, 'Warangal', 'Warangal, Telangana', 'Warangal Fort, built in the 13th century by the Kakatiya dynasty, stands as a testament to medieval Indian military architecture. The fort complex originally had three concentric circular walls, though only ruins remain today.', '13th century Kakatiya dynasty fortress | Iconic Kakatiya Kala Thoranam gateway | Stones fitted without mortar - engineering marvel | Three concentric defensive walls | Archaeological excavations site | Ancient temples and water management systems', 'October to March offers comfortable weather for exploring the expansive fort complex. Early mornings (6-9 AM) best for photography with soft sunlight.', 'Located in Warangal city center, 145 km from Hyderabad. Well connected by road (NH163) and rail. Warangal railway station is 5 km away. Local buses, autos, and taxis readily available.', 'Indians: ₹25, Foreigners: ₹300, Camera: Free', '9:00 AM to 5:30 PM, Open all days'),

(5, 'Lepakshi Temple', 'Temples', 'Lepakshi', 'images/Lepakshi/Lepakshi_Temple.jpg', 4.7, 13.80470000, 77.60890000, 'Sri Sathya Sai', 'Lepakshi, Andhra Pradesh', 'Lepakshi Temple, built in the 16th century during the Vijayanagara Empire, is renowned for its architectural wonders and exquisite artwork. The temple''s most famous feature is the "hanging pillar" - one of 70 pillars that doesn''t touch the ground completely.', 'Hanging pillar - architectural mystery | Largest monolithic Nandi statue in India (27 feet) | Stunning Vijayanagara era frescoes and paintings | Intricate stone carvings throughout complex | Mythological significance in Ramayana | 16th century architectural masterpiece', 'October to March when weather is pleasant. Weekdays less crowded. Early mornings ideal for detailed exploration and photography.', 'Located 120 km from Bangalore and 15 km from Hindupur. Accessible by road from Bangalore (2.5 hours), Tirupati (120 km), and Anantapur (38 km). Regular bus services available.', 'Free Entry', '6:00 AM to 8:00 PM, Open all days'),

(6, 'Ramappa Temple', 'Temples', 'Warangal', 'images/RamappaTemple/Ramappa temple.jpg', 4.7, 18.11670000, 79.93330000, 'Mulugu, Near Warangal', 'Warangal, Telangana', 'Ramappa Temple, also known as Ramalingeswara Temple, achieved UNESCO World Heritage Site status in 2021, recognizing its exceptional universal value. Built in 1213 CE by the Kakatiya dynasty, the temple is unique for being named after its sculptor Ramappa rather than the deity.', 'UNESCO World Heritage Site (2021) | Built with floating bricks technology | Named after sculptor Ramappa | 81 dancing poses carved on pillars | Earthquake-resistant sand foundation | 800-year-old engineering marvel', 'October to March offers ideal weather. Monsoon season (July-September) makes surroundings lush green. Early mornings provide best lighting for photography.', 'Located 77 km from Warangal, 209 km from Hyderabad. Accessible by road via Warangal. Buses available from Warangal to Palampet village (5 km from temple). Taxis recommended for convenient travel.', 'Free Entry (UNESCO site)', '6:00 AM to 8:00 PM, Open all days'),

(7, 'Chandragiri Fort', 'Forts', 'Chandragiri', 'images/ChandaragiriFort/Chandaragiri_fort.jpg', 4.4, 13.58330000, 79.31670000, 'Tirupati', 'Tirupati, Andhra Pradesh', 'Chandragiri Fort, built in the 11th century and strengthened by various dynasties, served as the fourth capital of the Vijayanagara Empire. The fort complex sits atop a 183-meter high hill, offering panoramic views of the surrounding landscape.', '11th century fort with Vijayanagara heritage | Two magnificent palaces - Raja Mahal and Rani Mahal | Panoramic hilltop views from 183 meters | Archaeological museum with rare artifacts | Historical significance in British India | Evening light and sound show', 'October to March when weather is pleasant for hilltop exploration. Light and sound show timings: 6:30 PM (Telugu) and 7:45 PM (English).', 'Located 15 km from Tirupati. Accessible by road from Tirupati (30 minutes). Regular bus services and taxis available. Nearest railway station: Tirupati (15 km).', 'Indians: ₹25, Foreigners: ₹300, Light & Sound Show: ₹50', '9:00 AM to 5:30 PM, Open all days'),

(8, 'Gudisa Hill Station', 'Hills', 'Maredumilli', 'images/GudisaHills/Gudisa_hill_station.jpg', 4.5, 18.33330000, 83.00000000, 'East Godavari', 'Maredumilli, Andhra Pradesh', 'Gudisa Hill Station, nestled in the Eastern Ghats near Maredumilli, is an emerging eco-tourism destination offering pristine natural beauty. The hill station provides spectacular sunrise and sunset views, with clouds often visible below the viewing points.', 'Pristine Eastern Ghats hill station | Spectacular cloud-covered valley views | Multiple trekking trails through dense forests | Bird watching paradise - 100+ species | Tribal village experiences | Unspoiled natural beauty', 'October to March for pleasant weather. November-January ideal for clear views and bird watching. Monsoon (June-September) makes trails slippery.', 'Located 30 km from Maredumilli. Nearest airport: Rajahmundry (100 km). Accessible by road from Rajahmundry (3 hours). Limited public transport; private vehicle or taxi recommended.', 'Entry: ₹30 per person, Vehicle: ₹50', '6:00 AM to 6:00 PM, Open all days'),

(9, 'Kapila Theertham Waterfalls', 'Waterfalls', 'Tirupati', 'images/KapilatTherdhamWaterfalls/Kapila_therdham_waterfalls.jpg', 4.3, 13.68330000, 79.35000000, 'Tirupati', 'Tirupati, Andhra Pradesh', 'Kapila Theertham is a sacred waterfall and temple complex located at the foothills of Tirumala hills. The waterfall, though moderate in size, holds immense religious significance as it is believed that sage Kapila meditated here.', 'Sacred waterfall with ancient Shiva temple | Mythological significance - Sage Kapila''s meditation site | Holy water believed to have healing properties | Dravidian temple architecture | Natural rock formations and pools | Peaceful pilgrimage destination', 'July to February when waterfall has good water flow. October-January ideal for comfortable weather. Avoid peak pilgrim rush during festivals.', 'Located 4 km from Tirupati city center. Easily accessible by road. Regular city buses, autos, and taxis available. Can be combined with Tirumala temple visit.', 'Temple Entry: Free, Offering optional', '6:00 AM to 6:00 PM, Open all days'),

(10, 'Laknavaram Lake Bridge', 'Lakes', 'Warangal', 'images/LaknavaramLakeBridge/Laknavaram_lake_bridge.jpg', 4.6, 18.03330000, 79.85000000, 'Mugulu, Near Warangal', 'Warangal, Telangana', 'Laknavaram Lake is a stunning 10,000-acre reservoir built around 13 interconnected islands, creating a unique landscape. The main attraction is the hanging bridge, extending 160 meters and connecting three islands, offering spectacular panoramic views of the lake and surrounding hills.', 'Unique 160-meter hanging bridge connecting islands | 10,000-acre picturesque reservoir | 13 interconnected islands creating scenic landscape | Boating activities: kayaking, pedal boats, speed boats | Bird watching paradise with migratory species | Spectacular sunset views over Western Ghats', 'October to March for pleasant weather and migratory birds. November-January best for bird watching. Weekdays less crowded than weekends.', 'Located 80 km from Warangal. Accessible by road from Warangal (2 hours), Hyderabad (180 km). Limited public transport; private vehicle recommended. Taxis available from Warangal.', 'Entry: ₹20 per person, Boating: ₹100-300 per person, Vehicle: ₹50', '9:00 AM to 5:30 PM, Open all days'),

(11, 'Maredumilli', 'Eco-Tourism', 'Maredumilli', 'images/Maredumilli/maredumilli.jpg', 4.5, 17.50000000, 81.75000000, 'East Godavari', 'Maredumilli, Andhra Pradesh', 'Maredumilli is a pristine eco-tourism destination situated in the Eastern Ghats, characterized by lush green forests, waterfalls, and rich biodiversity. The area is home to ancient medicinal plants and herbs, earning it recognition as an ecological hotspot.', 'Pristine Eastern Ghats biodiversity hotspot | Extensive bamboo forests and ancient trees | Multiple waterfalls: Jalatarangini, Amruthadhara | Tribal communities and cultural experiences | 40+ butterfly species | Medicinal plants and herbs garden', 'October to March offers pleasant weather for forest exploration. September-November when waterfalls are in full flow post-monsoon. Avoid heavy monsoon period.', 'Located 100 km from Rajahmundry. Accessible by road from Rajahmundry (3 hours). Nearest airport: Rajahmundry. Limited public buses; private vehicle or organized tours recommended.', 'Entry to eco-tourism spots: ₹30 per person, Vehicle: ₹50, Guided tours: ₹200-500', '6:00 AM to 6:00 PM, Open all days'),

(12, 'Lambasingi', 'Hills', 'Lambasingi', 'images/Lambasing/Lambasingi.jpg', 4.6, 17.81670000, 82.43330000, 'Visakhapatnam', 'Chintapalle, Andhra Pradesh', 'Lambasingi, often called the "Kashmir of Andhra Pradesh," is the only place in South India that experiences snowfall-like frost conditions. Located at an altitude of 1,025 meters, temperatures can drop to sub-zero levels during winter, creating a layer of frost on grass and vegetation.', 'Only South Indian location with frost/snow-like conditions | Sub-zero winter temperatures | Coffee, pepper, and cardamom plantations | Strawberry farming and fruit picking | Tribal village experiences | Mist-covered valleys and pine forests', 'November to February when frost occurs. December-January for coldest weather (0-5°C). Early morning hours (4-7 AM) best for frost viewing.', 'Located 100 km from Visakhapatnam. Accessible by road from Visakhapatnam (3 hours). Nearest railway: Visakhapatnam. Hire taxi or use organized tours. Road conditions good but winding.', 'Free Entry to village, Plantation visits: ₹100-200', 'Open 24/7, Best visited early morning for frost'),

(13, 'Kothapalli Waterfalls', 'Waterfalls', 'Gangaraju Madugula', 'images/KothapalliWaterfalls/Kothapalli_waterfalls.jpg', 4.4, 17.83330000, 82.36670000, 'Visakhapatnam', 'Visakhapatnam, Andhra Pradesh', 'Kothapalli Waterfalls is a hidden gem located in the lush forests of Visakhapatnam district. The waterfall cascades from approximately 40 feet height into a crystal-clear pool surrounded by rocky terrain and dense vegetation.', 'Secluded 40-feet waterfall in dense forest | Trekking through coffee plantations | Crystal-clear natural swimming pool | Rich biodiversity and bird watching | Tribal guide experiences | Perfect for nature photography', 'July to February when waterfall has good flow. October-January ideal weather for trekking. Monsoon makes trail slippery; avoid July-August peak rains.', 'Located 75 km from Visakhapatnam. Accessible by road to Madugula (65 km), then 2 km trek. Private vehicle or taxi recommended. Start early for day trip.', 'Entry: ₹20, Guide charges: ₹200-300, Parking: ₹50', '6:00 AM to 5:00 PM, Trekking not recommended after sunset'),

(14, 'Ponguleru Vaagu', 'Waterfalls', 'Warangal', 'images/PonguleruVaagu/Ponguleru_vaagu.jpg', 4.4, 17.95660000, 79.60210000, 'Warangal', 'Warangal, Telangana', 'Ponguleru Vaagu is a scenic water stream flowing through rocky terrain creating mini waterfalls and natural pools. The name "Vaagu" means stream in Telugu. This relatively lesser-known destination offers pristine natural beauty away from tourist crowds.', 'Scenic natural stream with mini waterfalls | Crystal-clear water over smooth rocks | Secluded location with minimal crowds | Perfect for picnics and photography | Sacred stream with local religious significance | Peaceful environment for nature therapy', 'July to February when water flow is good. October-January ideal weather. Monsoon (July-September) offers spectacular views but access may be difficult.', 'Located near Warangal city. Accessible by road from Warangal (25 km). Limited public transport; private vehicle recommended. Local inquiry needed for exact route.', 'Free Entry', 'Open 24/7, Daylight hours recommended for safety'),

(15, 'Armakonda Peak', 'Hills', 'Arma Konda', 'images/ArmakondaPeak/armakonda_peak.jpg', 4.5, 18.23330000, 82.76670000, 'Alluri, Near Visakhapatnam', 'Arma Konda, Andhra Pradesh', 'Armakonda, standing tall at 1,680 meters (5,512 feet), is the highest peak in Andhra Pradesh located in the Nallamala Hills range. The trek to the summit is challenging but rewarding, passing through dense forests, tribal settlements, and coffee plantations.', 'Highest peak in Andhra Pradesh at 5,512 feet | Challenging trek through dense forests | 360-degree panoramic Eastern Ghats views | Endemic Red Sanders trees | Tribal settlements and cultural interaction | Spectacular sunrise and stargazing', 'October to March ideal for trekking with comfortable weather. Avoid monsoon (June-September) due to slippery trails and leeches. December-February offers clear views.', 'Located 120 km from Visakhapatnam. Accessible by road to Paderu (base), then trek. Mandatory to hire local tribal guide. 2-day trek recommended with overnight camping.', 'Free Entry, Guide charges: ₹500-1000 per day, Camping permits required', 'Trekking start recommended at dawn, 4-6 hour ascent'),

(16, 'Tonkota Waterfalls', 'Waterfalls', 'Chittor', 'images/Tonkota_Waterfalls/tonkota_waterfalls.jpg', 4.3, 13.20000000, 79.10000000, 'Chittor', 'Sri Venkateswara National Park, Andhra Pradesh', 'Tonkota Waterfalls is a picturesque cascade located within the Sri Venkateswara National Park, making it a perfect blend of waterfall beauty and wildlife sanctuary. The waterfall drops approximately 30 feet into a natural pool surrounded by lush forest.', 'Waterfall within Sri Venkateswara National Park | 30-feet cascade with natural pool | Wildlife spotting opportunities | Trek through diverse ecosystems | Medicinal plant diversity | Untouched natural wilderness', 'July to February when waterfall has good flow and weather is pleasant. October-January ideal. Monsoon offers best water flow but park access may be restricted.', 'Located within Sri Venkateswara National Park. Accessible from Tirupati (60 km) via Chandragiri. Park entry requires permits. Private vehicle needed; limited public transport.', 'Park Entry: ₹20, Vehicle: ₹50, Camera: ₹25, Guide: ₹200', '6:00 AM to 5:00 PM, Closed during extreme weather'),

(17, 'Seetaramachandraswami Temple', 'Temples', 'Bhadrachalam', 'images/Seetaramachandraswami Temple, Samshabad/seetaramachandraswami_temple.jpg', 4.5, 17.66670000, 80.88330000, 'Bhadrachalam', 'Bhadrachalam, Telangana', 'Seetaramachandraswami Temple, located on the banks of the Godavari River in Bhadrachalam, is one of the most important Rama temples in South India. The temple has deep mythological significance as it is believed to be the site where Lord Rama, along with Sita and Lakshmana, stayed during their exile.', 'One of most important Rama temples in India | Mythological significance from Ramayana | Built by Bhakta Ramadasu in 17th century | Grand Rama Navami celebrations | Beautiful Godavari riverfront location | Ancient artifacts and temple museum', 'October to March for comfortable weather. Rama Navami (March/April) for grand festival experience. Avoid peak summer heat (April-June).', 'Located in Bhadrachalam, 312 km from Hyderabad. Accessible by road and rail. Bhadrachalam Road railway station 40 km away. Regular bus services from major cities. River crossing by boat also available.', 'Free Entry, Special darshan: ₹50', '4:00 AM to 12:00 PM, 3:00 PM to 9:00 PM'),

(18, 'Tribal Village', 'Villages', 'Warangal', 'images/TribalVillageNear Armakonda/tribal_village.jpg', 4.4, 17.95660000, 79.60210000, 'Warangal', 'Warangal, Telangana', 'The tribal villages near Armakonda offer authentic cultural experiences showcasing the traditional lifestyle of indigenous communities. These villages, primarily inhabited by Konda Reddy and Koya tribes, maintain age-old customs, traditional architecture, and sustainable living practices.', 'Authentic tribal community experience | Traditional hut architecture with bamboo and leaves | Organic farming and sustainable practices | Traditional tribal dances and festivals | Unique tribal crafts and textiles | Traditional medicinal plant knowledge', 'October to March for comfortable weather and festival season. Harvest festivals (December-January) offer best cultural experiences. Prior permission from tribal welfare department recommended.', 'Located in forest areas near Warangal and Armakonda. Access requires local guidance. Reach Warangal, then hire local guide. Respect tribal customs; photography requires permission.', 'Free Entry, Donations appreciated for community development', 'Visit during daylight hours (8 AM to 5 PM)'),

(19, 'Puttakonda Temple', 'Temples', 'Puttakonda village', 'images/Puttakonda/Puttakonda.jpeg', 4.3, 16.91660000, 82.10330000, 'East Godavari', 'Kakinada, Andhra Pradesh', 'Puttakonda Temple is an ancient Hindu temple with rich mythological history, believed to be thousands of years old. According to local legends, the temple is associated with Sage Agastya and various Puranic stories.', 'Ancient temple with mythological significance | Associated with Sage Agastya | Grand Rathotsavam chariot festival | Classical Andhra temple architecture | Sacred temple pond | Ancient inscriptions and historical value', 'Throughout the year for regular worship. Rathotsavam during Bhimana Amavasya (February/March) for festival experience. Maha Shivaratri also significant.', 'Located 20 km from Kakinada and 12 km from Bikkavolu. Accessible by road from Kakinada. Regular bus services available. Auto-rickshaws from nearby towns.', 'No entry fee, Offerings optional', '6:00 AM to 8:00 PM, Extended hours during festivals'),

(20, 'Araku Valley', 'Valleys', 'Araku Valley', 'images/ArakuValley/Araku_Valley1.jpg', 4.7, 18.32730000, 82.87500000, 'Visakhapatnam', 'Araku, Andhra Pradesh', 'Araku Valley is a spectacular hill station located in the Eastern Ghats at an altitude of 1,300 meters, offering breathtaking scenic beauty and pleasant climate year-round. The valley is famous for its extensive coffee plantations producing some of India''s finest organic coffee.', 'Scenic hill station at 1,300 meters elevation | Famous for organic coffee plantations | Spectacular train journey from Visakhapatnam | Tribal Museum showcasing indigenous culture | Padmapuram Gardens with tree-top huts | Adventure activities and trekking trails', 'October to March offers pleasant weather (15-25°C). December-January coldest and most comfortable. Monsoon (June-September) makes landscape lush but can hinder activities.', 'Accessible by scenic train from Visakhapatnam (4 hours) or road (115 km, 3 hours). Train journey highly recommended for views. Regular bus services available. Nearest airport: Visakhapatnam.', 'Entry to specific attractions: ₹30-50, Gardens: ₹20, Museum: ₹10', 'Most attractions: 9:00 AM to 6:00 PM'),

(21, 'Borra Caves', 'Caves', 'Araku Valley', 'images/BorraCaves/borra_caves.webp', 4.6, 18.28330000, 83.06670000, 'Visakhapatnam', 'Araku, Andhra Pradesh', 'Borra Caves are million-year-old natural limestone formations located at an altitude of 705 meters in the Ananthagiri hills. Discovered in 1807 by British geologist William King, these caves extend to a depth of 80 meters and are renowned for their stunning stalactite and stalagmite formations.', 'Million-year-old natural limestone caves | Stunning stalactite and stalagmite formations | 80 meters deep cave system | Natural formations resembling various shapes | Colored illumination enhancing beauty | Geological and scientific significance', 'October to March ideal weather. Avoid monsoon (June-September) as caves may be slippery. Weekdays less crowded than weekends.', 'Located 29 km from Araku Valley, 92 km from Visakhapatnam. Accessible by road or train (Borra Guhalu station). Can be combined with Araku Valley trip. Taxis and buses available.', 'Indians: ₹45, Foreigners: ₹300, Camera: ₹50, Parking: ₹20', '10:00 AM to 5:30 PM, Closed on Mondays'),

(22, 'Simhachalam Temple', 'Temples', 'Visakhapatnam', 'images/Simhachalam_Temple/simhachalam_temple1.webp', 4.8, 17.76020000, 83.24540000, 'Visakhapatnam', 'Visakhapatnam, Andhra Pradesh', 'Simhachalam Temple, dedicated to Lord Varaha Narasimha (an incarnation of Lord Vishnu), is one of the most revered Vaishnavite temples in India. Built in the 11th century, the temple showcases magnificent Kalinga architecture with intricate carvings covering every inch of the structure.', 'Ancient Vaishnavite temple from 11th century | Magnificent Kalinga architecture | Hilltop location with panoramic city views | Unique Chandanotsavam festival | Deity covered with sandalwood paste year-round | Intricate carvings and sculptural excellence', 'October to March for comfortable weather. Chandanotsavam (Akshaya Tritiya - April/May) for special darshan. Early mornings (4-7 AM) less crowded.', 'Located 16 km from Visakhapatnam city center. Well connected by road. Regular city buses, autos, and taxis available. Nearest railway: Simhachalam station (2 km).', 'Free Entry, Special darshan: ₹100-500', '4:00 AM to 9:00 PM, Extended hours during festivals'),

(23, 'Kailasagiri', 'Hills', 'Visakhapatnam', 'images/Kailasgiri/kailasgiri.webp', 4.5, 17.73520000, 83.36440000, 'Visakhapatnam', 'Visakhapatnam, Andhra Pradesh', 'Kailasagiri is a beautifully developed hilltop park spanning 380 acres, offering spectacular 360-degree views of Visakhapatnam city and the Bay of Bengal coastline. The main attraction is the massive 40-feet tall statue of Lord Shiva and Goddess Parvati, visible from various parts of the city.', '380-acre hilltop park with panoramic views | 40-feet Shiva-Parvati statue | Exciting ropeway ride with aerial city views | Multiple viewpoints including Titanic point | Landscaped gardens and floral clock | Spectacular sunset over Bay of Bengal', 'October to March for pleasant weather. Evenings (4-7 PM) ideal for sunset views. Weekdays less crowded. Avoid rainy days for ropeway safety.', 'Located in Visakhapatnam city. Ropeway base station near Beach Road. Accessible by road (winding hill road) or ropeway. City buses, autos, and taxis readily available.', 'Entry: ₹50, Ropeway: ₹100 (round trip), Parking: ₹30', '10:00 AM to 8:00 PM, Extended hours on weekends'),

(24, 'RK Beach', 'Beaches', 'Visakhapatnam', 'images/Rk_Beach/rk_beach.webp', 4.6, 17.72310000, 83.32700000, 'Visakhapatnam', 'Visakhapatnam, Andhra Pradesh', 'Ramakrishna Beach (RK Beach) is Visakhapatnam''s most popular urban beach stretching along the Bay of Bengal coastline. The beach is famous for housing INS Kursura Submarine Museum - India''s first submarine museum where visitors can explore the actual submarine used in wars.', 'Popular urban beach with wide sandy shore | INS Kursura Submarine Museum | Kali Temple on sea rock | Water sports: jet skiing, parasailing | Scenic beach promenade | Vibrant evening atmosphere with food stalls', 'Throughout the year. October to March most comfortable. Evenings (4-8 PM) best for pleasant weather and atmosphere. Early mornings good for peaceful walks.', 'Located in Visakhapatnam city center along Beach Road. Easily accessible by city buses, autos, taxis. Walking distance from many city hotels. Parking available.', 'Beach Access: Free, Submarine Museum: ₹40 (Indians), ₹100 (Foreigners), Water sports: ₹200-500', 'Beach: 24/7, Museum: 2:00 PM to 8:30 PM (Closed Monday)'),

(25, 'Rushikonda Beach', 'Beaches', 'Visakhapatnam', 'images/Rushikonda_Beach/Rushikonda_beach.webp', 4.5, 17.78280000, 83.38500000, 'Visakhapatnam', 'Visakhapatnam, Andhra Pradesh', 'Rushikonda Beach is considered one of the most pristine and beautiful beaches on the east coast of India. The golden sandy beach stretches for over a kilometer with clear blue waters ideal for swimming.', 'Pristine beach with golden sands | Protected bay formation with hills backdrop | Water sports hub: windsurfing, jet skiing | Clear waters ideal for swimming | National water sports events venue | Spectacular sunrise views', 'October to March ideal for water sports and beach activities. April-June hot but good for water sports. Avoid rough sea during monsoon (June-August).', 'Located 8 km from Visakhapatnam city center. Easily accessible by road. Regular city buses and taxis available. 15-minute drive from RK Beach.', 'Beach Access: Free, Water sports: ₹200-800 depending on activity, Parking: ₹20', 'Open 24/7, Water sports: 9:00 AM to 6:00 PM'),

(26, 'Yarada Beach', 'Beaches', 'Visakhapatnam', 'images/Yarada_Beach/Yarada_Beach.webp', 4.4, 17.65220000, 83.27660000, 'Visakhapatnam', 'Visakhapatnam, Andhra Pradesh', 'Yarada Beach is a secluded and serene beach offering tranquility away from the crowded city beaches. The unique feature is the beach being nestled between the Eastern Ghats hills and the Bay of Bengal, creating a stunning natural amphitheater.', 'Secluded beach surrounded by hills | Unique hills-meet-sea landscape | Peaceful atmosphere with minimal crowds | Perfect for photography and meditation | Occasional dolphin sightings | Scenic coastal drive', 'October to March for comfortable weather. Early mornings (6-9 AM) offer best peaceful experience. Avoid monsoon for safety.', 'Located 15 km from Visakhapatnam city. Accessible by road via Gangavaram. Taxis and private vehicles recommended as public transport limited. 30-minute scenic drive from city.', 'Free Entry', '6:00 AM to 6:00 PM recommended, Swimming not advised due to currents'),

(27, 'Tyda Nature Camp', 'Eco-Tourism', 'Visakhapatnam', 'images/carousel-img3.jpg', 4.3, 17.91670000, 82.75000000, 'Visakhapatnam', 'Ananthagiri, Andhra Pradesh', 'Tyda Nature Camp is an eco-tourism destination nestled in the Eastern Ghats, offering adventure activities and nature experiences. Managed by Andhra Pradesh Tourism, the camp provides various adventure sports including zip-lining (one of India''s longest at 600 meters), rappelling, rope bridges, and trekking.', 'Eco-tourism with adventure activities | 600-meter zip-line (one of India''s longest) | Rappelling, rope bridges, trekking | Bird watching and nature trails | Camping amidst dense forest | Tribal village cultural experiences', 'October to March ideal for adventure activities and camping. Weekends and holidays see more activity schedules. Monsoon (June-September) activities restricted.', 'Located 52 km from Visakhapatnam in Ananthagiri hills. Accessible by road (2-hour drive). Private vehicle recommended. AP Tourism packages available from Visakhapatnam including transport.', 'Entry: ₹50, Adventure activities: ₹200-500 per activity, Camping: ₹500-1000 per night', '9:00 AM to 5:00 PM for day visitors, Camping overnight available'),

(28, 'Srikurmam Temple', 'Temples', 'Srikakulam', 'images/SrikurmamTemple/srikurmam_temple1.webp', 4.6, 18.28330000, 84.11670000, 'Srikakulam', 'Srikurmam, Andhra Pradesh', 'Srikurmam Temple is one of the rarest temples in India dedicated to Lord Vishnu''s Kurma (tortoise) avatar, making it of immense religious and architectural significance. The temple dates back to the 4th-5th century CE and showcases ancient Kalinga-style architecture.', 'Rare temple dedicated to Kurma avatar | Ancient 4th-5th century architecture | One of only two Kurma temples in India | Kalinga architectural style | Mythological Samudra Manthan significance | Archaeological importance with ancient inscriptions', 'October to March for comfortable weather. Festival times (Kalyanotsavam) for cultural experience. Early mornings peaceful for detailed exploration.', 'Located 13 km from Srikakulam town. Accessible by road from Srikakulam. Regular bus services available. Nearest railway: Srikakulam Road (16 km). Taxis and autos available.', 'Free Entry', '6:00 AM to 8:00 PM, Open all days'),

(29, 'Arasavilli Sun Temple', 'Temples', 'Srikakulam', 'images/ArasavalliSunTemple/arasavalli_sun_temple1.webp', 4.5, 18.35000000, 84.13330000, 'Srikakulam', 'Arasavalli, Andhra Pradesh', 'Arasavilli Sun Temple is one of the two famous Sun temples in India (other being Konark), with a history dating back to the 7th century CE. The temple is dedicated to Surya (Sun God) and features the unique architectural element of a shadow clock (time-measuring device using sunlight).', 'One of India''s rare Sun temples | 7th century ancient architecture | Unique shadow clock mechanism | Beautiful Surya idol with seven horses | Astronomical and astrological significance | Therapeutic temple tank', 'Throughout the year. Sunday mornings special as shadow falls on deity. Ratha Saptami (January/February) for grand celebrations. October-March pleasant weather.', 'Located 1 km from Srikakulam town center. Easily accessible by road. Regular city buses, autos, and taxis. Nearest railway: Srikakulam Road (13 km).', 'Free Entry', '6:00 AM to 8:00 PM, Sunday mornings particularly auspicious'),

(30, 'Papi Hills', 'Hills', 'East Godavari', 'images/PapiHills/papi_hills1.webp', 4.6, 17.41670000, 81.58330000, 'East Godavari', 'Rajahmundry, Andhra Pradesh', 'Papi Hills are a scenic range of hills along the Godavari River, accessible only by boat, making the journey itself an unforgettable experience. The boat journey from Rajahmundry through the gorge takes 3-4 hours, passing through stunning landscapes where hills rise dramatically from both sides of the river.', 'Scenic hills accessible only by boat | 3-4 hour unforgettable Godavari boat journey | Dramatic gorge landscapes | Remote tribal areas and villages | Monsoon waterfalls cascading from hills | Spiritual significance with cleansing belief', 'October to March ideal for comfortable boat journey. Post-monsoon (September-November) offers lush greenery and waterfalls. Avoid peak monsoon due to strong currents.', 'Start from Rajahmundry. Boats depart from Rajahmundry boat jetty. Pre-booking recommended. Private boats: ₹3000-4000, Shared boats available. Full day trip required. Return by afternoon.', 'Boat charges: ₹1500-3000 per boat (6-10 persons), Individual tickets on shared boats: ₹300-500', 'Boats start: 6:00 AM to 8:00 AM, Return by 2:00 PM'),

(31, 'Coringa Wildlife Sanctuary', 'Wildlife', 'East Godavari', 'images/coringa_wildlife/coringa_wildlife1.webp', 4.4, 16.78330000, 82.26670000, 'East Godavari', 'Kakinada, Andhra Pradesh', 'Coringa Wildlife Sanctuary is the second-largest mangrove forest in India, spreading over 235 square kilometers at the Godavari River delta. This biodiversity hotspot is home to endangered Fishing Cat, Smooth Indian Otter, and over 120 bird species including migratory birds that visit during winter.', 'Second-largest mangrove forest in India | 235 sq km biodiversity hotspot | 120+ bird species including migratory ones | Endangered species: Fishing Cat, Smooth Otter | Boat safaris through mangrove channels | Crucial coastal ecosystem protection', 'November to February when migratory birds arrive. Early mornings (6-9 AM) best for bird watching. Pleasant weather October-March. Avoid monsoon and cyclone seasons.', 'Located 20 km from Kakinada. Accessible by road to Kakinada, then boat from jetty. Private vehicles can reach nearby villages. Organized tours available from Kakinada.', 'Entry: ₹25, Boat safari: ₹500-800 per boat, Camera: ₹50, Guide charges: ₹200', '6:00 AM to 5:00 PM, Boat safaris start early morning'),

(32, 'Kakinada Beach', 'Beaches', 'Kakinada', 'images/KakinadaBeach/kakinada_beach1.webp', 4.3, 16.93330000, 82.25000000, 'East Godavari', 'Kakinada, Andhra Pradesh', 'Kakinada Beach is a serene and picturesque beach featuring a distinctive red and white lighthouse that has become the city''s landmark. The beach offers unique views where mangrove-fringed coastline meets the Bay of Bengal.', 'Distinctive red-white lighthouse landmark | Unique mangrove-fringed coastline | Rocky shore with natural formations | Peaceful less-commercialized beach | Fishing community culture | Spectacular lighthouse sunset views', 'Throughout the year. October to March most comfortable weather. Evenings (4-7 PM) ideal for sunset and pleasant breeze. Early mornings to watch fishing boats.', 'Located in Kakinada city. Easily accessible by road. Kakinada is well connected by road and rail. Regular city buses and autos available. Parking facilities available near beach.', 'Free Entry', 'Open 24/7, Best visited during daylight and early evening');

-- ============================================================================
-- DATA FOR TABLE: place_images (36 gallery images for places)
-- ============================================================================
-- Gallery images for each destination

INSERT INTO place_images (id, place_id, image_url, caption) VALUES
(1, 1, 'images/1000Pillars/1000pillars_1.jpg', 'Pillar details 1'),
(2, 1, 'images/1000Pillars/1000pillars_2.jpg', 'Pillar details 2'),
(3, 1, 'images/1000Pillars/1000pillerstemple.jpg', 'Full temple view'),
(12, 2, 'images/HorselyHills/Horsely_hills.jpg', 'Hill landscape'),
(32, 3, 'images/Thalakona_Waterfalls/Thalakona_waterfalls.jpg', 'Waterfall view'),
(35, 4, 'images/Warangal_Fort/Warangal_Fort.jpg', 'Fort structure'),
(20, 5, 'images/Lepakshi/Lepakshi_Temple.jpg', 'Temple architecture'),
(21, 5, 'images/Lepakshi/Lepakshi_Nandi.jpg', 'Sacred Nandi sculpture'),
(26, 6, 'images/RamappaTemple/Ramappa temple.jpg', 'Temple structure'),
(8, 7, 'images/ChandaragiriFort/Chandaragiri_fort.jpg', 'Fort main view'),
(9, 7, 'images/ChandaragiriFort/Chandaragiri_fort2.jpg', 'Fort structure'),
(11, 8, 'images/GudisaHills/Gudisa_hill_station.jpg', 'Hill station view'),
(15, 9, 'images/KapilatTherdhamWaterfalls/Kapila_therdham_waterfalls.jpg', 'Waterfall view'),
(17, 10, 'images/LaknavaramLakeBridge/Laknavaram_lake_bridge.jpg', 'Lake bridge view'),
(18, 10, 'images/LaknavaramLakeBridge/Laknavaram_lake_bridge.jpg', 'Lake landscape'),
(22, 11, 'images/Maredumilli/maredumilli.jpg', 'Forest view'),
(19, 12, 'images/Lambasing/Lambasingi.jpg', 'Hill station view'),
(16, 13, 'images/KothapalliWaterfalls/Kothapalli_waterfalls.jpg', 'Waterfall cascade'),
(24, 14, 'images/PonguleruVaagu/Ponguleru_vaagu.jpg', 'Valley view'),
(6, 15, 'images/ArmakondaPeak/Armakonda_peak.jpg', 'Peak landscape'),
(33, 16, 'images/Tonkota_Waterfalls/tonkota_waterfalls.jpg', 'Waterfall cascade'),
(29, 17, 'images/Seetaramachandraswami Temple, Samshabad/Seetaramachandraswami Temple, Samshabad.jpg', 'Temple view'),
(34, 18, 'images/TribalVillageNear Armakonda/Tribal village near armakonda.jpg', 'Village view'),
(25, 19, 'images/Puttakonda/Puttakonda.jpeg', 'Temple view'),
(4, 20, 'images/ArakuValley/Araku_Valley1.jpg', 'Valley landscape'),
(7, 21, 'images/BorraCaves/borra_caves.webp', 'Cave formations'),
(30, 22, 'images/Simhachalam_Temple/simhachalam_temple1.webp', 'Temple complex'),
(13, 23, 'images/Kailasgiri/kailasgiri.webp', 'Spiritual site'),
(27, 24, 'images/Rk_Beach/rk_beach.webp', 'Beach landscape'),
(28, 25, 'images/Rushikonda_Beach/Rushikonda_beach.webp', 'Beach view'),
(36, 26, 'images/Yarada_Beach/Yarada_Beach.webp', 'Beach landscape'),
(31, 28, 'images/SrikurmamTemple/srikurmam_temple1.webp', 'Sacred temple'),
(5, 29, 'images/ArasavalliSunTemple/arasavalli_sun_temple1.webp', 'Sun temple view'),
(23, 30, 'images/PapiHills/papi_hills1.webp', 'Hills landscape'),
(10, 31, 'images/coringa_wildlife/coringa_wildlife1.webp', 'Wildlife area'),
(14, 32, 'images/KakinadaBeach/kakinada_beach1.webp', 'Beach view');

-- ============================================================================
-- NOTES FOR CONTENT UPDATES
-- ============================================================================